### ISSUE TITLE
Linked in redesign feedback

### ISSUE THREAD

**Issue by ghost** [davidpowellme/linkedin#1]
Everything on both your designs is awesome..very user friendly! The feedback I'm giving is for the government design. The only thing I can think of is perhaps adding a hover state(or making a link) to more things. All the buttons are hoverable but like the icon, top nav links, and then the bottom nav section could all be links. Also, maybe add some information about the graph at the top so users know what it's about. Oh and perhaps centering the copyright in the footer might look better. 

Love your work and redesign concepts!

**Comment by davidpowellme** [comment]
Thanks, that was definitely necessary. Added hover effects and graph!
