### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by amaliebarras** [davidpowellme/linkedin#2]
I love the textures on the divs, reminds me of sticky notes. I also love the "upcoming meeting" calendar integration idea, super thoughtful.

The following are really picky things bc I want to give ya something useful :) 
- [ ] I know it's dummy text, but you have a typo which would be an easy fix & show attention to detail
  "See what's new is his professional story"
- [ ] Under the "people you may know", the alignment of the photo is off from the text, looks like padding maybe?
- [ ] None of the links look very clickable - I'd recommend adding hover states even if they aren't in the styleguide, but I'm kind of a rulebreaker like that sooooooo 

Overall awesome work as always dude

**Comment by davidpowellme** [comment]
Added hover, fixed typo, and fixed alignment.
